# Generated by Django 4.2.1 on 2023-07-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('Dept_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('Manager', models.IntegerField()),
                ('Hire_date', models.DateField()),
                ('Salary', models.IntegerField()),
                ('Dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Life.department')),
            ],
        ),
    ]
